### ISSUE TITLE
[Volunteer] The number of seniors in Vol profile is calculated incorrectly

### ISSUE THREAD

**Issue by Tara812** [yoshan0921/Favr#139]
Cocoy has 7 favors completed for 2 elders, which are John and Betsie. However in Cocoy's profile, he has helped only 1 elder.
<img width="759" alt="Screenshot 2024-07-13 at 4 39 30 PM" src="https://github.com/user-attachments/assets/2bb4fc18-7fa4-4f73-992f-564e9fc831a8">
<img width="525" alt="Screenshot 2024-07-13 at 4 30 58 PM" src="https://github.com/user-attachments/assets/e729e500-68a9-463d-80d6-a33baa474017">

**Comment by yoshan0921** [comment]
I fixed this issue. The condition was changed from when this bug was reported, but Cocoy had 6 completed tasks from a total of 2 seniors.

![Image](https://github.com/user-attachments/assets/a4b66c8a-517f-42ec-b6e4-3091f9fb82ee)

![Image](https://github.com/user-attachments/assets/46107fcb-66a9-4ee3-9541-b2b9563580f9)
